# Generated by Django 5.1.15 on 2026-06-22 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('meeting_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('meeting_time', models.TimeField()),
                ('pin', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='attendance.caregroup')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('group', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='attendance.caregroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('meeting_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='attendance.meetingdate')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('meeting_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.meetingdate')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.member')),
            ],
            options={
                'unique_together': {('meeting_date', 'member')},
            },
        ),
    ]
