# Generated by Django 5.1.15 on 2026-06-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
